name: REUSE

on:
  workflow_call:

permissions:
  contents: read

jobs:
  reuse:
    name: REUSE licensing compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: fsfe/reuse-action@v6
